config/routes.rb
 Rails.application.routes.draw do

  devise_for :views
  root to: 'pages#home'
  get 'dashboard', to: "dashboards#home", as: :dashboard

  devise_for :users

  # get '/bars/:city', to: 'bars#city', constraints: { city: /[[:alpha:]]+/ }
  resources :bars, only: [:index, :show, :new, :create] do
    resources :reservations, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  
  resources :reservations, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  def full_address
    [address, city.capitalize, 'France'].compact.join(', ')
  end

  def rating
    ratings = []
    if reviews.any?
      reviews.each do |review|
        ratings << review.rating
      end
    end
    if ratings != []
      average = ratings.sum / ratings.size.to_f
      return average.round(1)
    else
      return 0
    end
  end
  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo
  belongs_to :owner, class_name: 'User'
  has_many  :reviews, dependent: :destroy
  has_many  :reservations, dependent: :destroy
  validates :name, uniqueness: { scope: :address }
  validates :name, :capacity, :ambiance, :address, :city, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :bar
  validates :date, uniqueness: { scope: :bar_id, message: "not available my friend !" }
  validates :user_id, :bar_id, :date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bar

  RATING = (0..5)
  # validates :user_id, uniqueness: { scope: :bar_id }
  validates :user_id, :bar_id, :content, :rating, presence: true
  validates :rating, inclusion: { in: RATING }
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :bars, foreign_key: :owner_id
  has_many  :reservations
  has_many  :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    cookies[:search] = params[:city]
    puts cookies[:search]
    @bars = Bar.where("city ILIKE :query", query: "#{params[:city]}%").geocoded
    @bars = @bars.where(ambiance: params[:ambiance]) if params[:ambiance]
    @markers = @bars.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bar: bar }),
        image_url: helpers.asset_url('marker_beer.png')
      }
    end
  end

  def show
    @search = cookies[:search]
    @bar = Bar.find(params[:id])
  end

  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)
    @bar.owner = current_user
    if @bar.save
      redirect_to dashboard_path, notice: 'Bar successfully created'
    else
      render :new
    end
  end

    private

  def bar_params
    params.require(:bar).permit(:name, :capacity, :ambiance, :address, :city.downcase, :photo, :price, :description)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def home
    @current_user = current_user
    @reservations = @current_user.reservations
    @bars = @current_user.bars
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bar, only: [:new, :create]

  def new
    @reservation = Reservation.new
  end

  def create
    @bar = Bar.find(params[:bar_id])
    @reservation = @bar.reservations.build(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.save
      redirect_to dashboard_path, notice: "Reservation successful, see you soon my friend !"
    else
      flash.now[:alert] = "The bar is already booked for this date !"
      render :new
    end
  end

  private

  def set_bar
    @bar = Bar.find(params[:bar_id])
  end

  def reservation_params
    params.require(:reservation).permit(:date)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
    @bar = Bar.find(params[:bar_id])
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.bar = Bar.find(params[:bar_id])
    if @review.save
      redirect_to dashboard_path(@review)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :user_id, :bar_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def back_button_path(search)
    if search.blank?
      root_path
    else
      bars_path(city: search)
    end
  end

  def owner?(user)
    user.bars.any?
  end

  def renter?(user)
    user.reservations.any?
  end

  def address(bar)
    return "#{bar.address}, #{bar.city}"
  end

  def total_reservations(bar)
    x = 0
    bar.reservations.each do |r|
      x +=1
    end
    return x
  end

  def next_reservation(bar)
    if bar.reservations.any?
      bar.reservations.sort{ |a,b| a.date <=> b.date }.first.date
    else
      return "--"
    end
  end

  def rating(bar)
    ratings = []
    if bar.reviews.any?
      bar.reviews.each do |review|
        ratings << review.rating
      end
    end
    if ratings != []
      average = ratings.sum / ratings.size.to_f
      return "#{average.round(1)} / 5"
    else
      return "- / 5"
    end
  end

  def coming?(reservation)
    if reservation.date > Date.today
      return "coming"
    else
      return "passed"
    end
  end

end

app/views/bars/_info_window.html.erb
<h2><%= link_to bar.name, bar_path(bar) %></h2>
<p><%= bar.address %></p>
<p><%= rating(bar) %></p>

app/views/bars/create.html.erb
<h1>Bars#create</h1>
<p>Find me in app/views/bars/create.html.erb</p>

app/views/bars/index.html.erb
<div class="container">
    <div id="map" style="width: 100%; height: 600px; margin-top: 30px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <%if (params[:city].present?) %>
        <h1><%= "Bars for the city of #{params[:city].capitalize}" %></h1>
      <% else %>
        <h1><%= "The list of Bars" %></h1>
      <% end %>
    </div>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: rgb(10, 219, 182)">
        All atmospheres 💃🕺
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <% mood = %w[Electro Punk Reggae Hip-hop Jazz Hot] %>
        <% mood.each do |m| %>
          <%= link_to m, {city: params[:city], ambiance: m}, class: 'dropdown-item' %>
        <% end %>
      </div>
    </div>
  </div>

    <div class="row m-0 d-flex justify-content-between">
        <% sorted_bars = @bars.sort_by { |a| a.rating }.reverse %>
        <% sorted_bars.each do |bar| %>
        <div class="card mr-3 mb-5 shadow-lg shadow bg-white rounded" style="width: 20rem;">
            <%= image_tag bar.photo, class: "img" %>
            <div class=average-text>
              <p class= average-number>
                <%= rating(bar) %>
              </p>
            </div>
            <div class="card-body">
                <h5 class="card-title text-truncate"><%= bar.name %></h5>

                <p class="card-text text-truncate"><%= bar.ambiance%></p>


                <div class="buttons">
                    <%= link_to 'See more details', bar_path(bar), class: "btn btn-outline-primary" %>
                    <%= link_to 'Book It', new_bar_reservation_path(bar), class: "btn btn-outline-primary" %>
                </div>
            </div>
        </div>
        <% end %>

    </div>
</div>

app/views/bars/new.html.erb
<div class="container">

    <h1>Ajouter un bar</h1>
    <%= simple_form_for @bar do |f| %>
    <%= f.input :name, placeholder: 'Enter the name' %>
    <%= f.input :capacity, as: :numeric, placeholder: 'Enter the capacity' %>
    <%= f.input :ambiance, placeholder: 'Enter the ambiance' %>
    <%= f.input :address, placeholder: 'Enter the address' %>
    <%= f.input :city, placeholder: 'Enter the city' %>
    <%= f.input :price, placeholder: 'Enter the price' %>
    <%= f.input :description, as: :text, placeholder: 'Enter the description' %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: 'btn-primary' %>
    <% end %>

</div>

app/views/bars/show.html.erb
<div class="container">

    <h1><%= @bar.name %></h1>

    <div class="card mb-2">
        <%= link_to "Book it", new_bar_reservation_path(@bar), class: "btn btn-primary" ,style: "position: absolute; top: 30px; right: 30px"  %>
        <%= link_to "Back to search", back_button_path(@search), class: "btn btn-primary" ,style: "position: absolute; top: 30px; left: 30px"  %>
        <%if @bar.photo.attached?%>
    </div>
        
        
        <%= image_tag @bar.photo, class: "card-img-top", style: "height: 400px; margin-bottom: 50px; object-fit: cover" %>
        


        <% end %>
        <p class="card-text-description"><small><%= @bar.description %></small></p>


        <div class="card-body">
            <div class="row m-0 d-flex justify-content-between">
                <h5 class="card-title">Capacity : <%= @bar.capacity %></h5>
                <h5 class="card-title">Price : <%= @bar.price %> $</h5>
                <h5 class="card-title"><%= "Rating : #{rating(@bar)}" %></h5>

            </div>

            <p class="card-text">Ambiance : <%= @bar.ambiance.capitalize %></p>

            <p class="card-text">Address : <%= @bar.address %></p>
            <p class="card-text">City : <%= @bar.city.capitalize %></p>
        </div>
    


    <ul class="list-group">
        <% @bar.reviews.each do |review| %>
        <li class="list-group-item">
            <table>
                <tbody>
                    <col width="140px" />
                    <col width=auto />
                    <col width="60px" />
                    <tr>
                        <td>
                            <p class="review_main"><%= User.find(review.user_id).first_name %></p>
                            <p class="text-muted"><%= review.created_at.strftime('%Y-%m-%d')%></p>
                        </td>
                        <td class="review_content"><%= review.content %></td>
                        <td class="review_main"><%= review.rating %> / 5</td>
                    </tr>
                </tbody>
            </table>
        </li>
        <% end %>

app/views/dashboards/home.html.erb
<div class="dashboard-main d-flex">
<div class="dashboard">

<h1><%= "Dashboard #{@current_user.first_name}" %></h1>

  <% if renter?(@current_user) %>
    <h2>My reservations</h2>

    <div class="tbl-header">
      <table cellpadding="0" cellspacing="0" border="0">
        <thead>
          <tr>
            <th>For</th>
            <th>Bar name</th>
            <th>Made</th>
          </tr>
        </thead>
      </table>
    </div>

    <div class="tbl-content">
      <table cellpadding="0" cellspacing="0" border="0">
        <tbody>
          <% @reservations.each do |reservation| %>
          <% bar = Bar.find(reservation.bar_id) %>
            <tr class="<%=coming?(reservation) %>">
              <td><%= reservation.date.strftime('%Y-%m-%d') %></td>
              <td><%= link_to "#{bar.name}", bar_path(bar)  %><small><em><%= link_to "     (Let a review)", new_bar_review_path(reservation.bar) %></em></small></td>
              <td><%= reservation.created_at.strftime('%Y-%m-%d') %></td>
              <!-- <td><%#= link_to 'Edit', edit_reservation_path(flat) %></td> -->
              <!-- <td><%#= link_to 'Cancel', "", method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  <% end %>

  <% if owner?(@current_user) %>
    <h2>Mes bars</h2>
    <div class="tbl-header">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>Added</th>
          <th>Total reservations</th>
          <th>Next reservation</th>
        </tr>
      </thead>
    </table>
    </div>

    <div class="tbl-content">
    <table>
      <tbody>
        <% @bars.each do |bar| %>
        <tr>
          <td>
          <%= link_to bar.name, bar_path(bar.id)%>
          </td>
          <td><%= address(bar) %></td>
          <td><%= bar.created_at.strftime('%Y-%m-%d') %></td>
          <td><%= total_reservations(bar) %></td>
          <td><%= next_reservation(bar) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>

  <% end %>
</div>
<div class="mojito">
  <div class="wrapper">
 <div class="cocktail">
   <div class="liquid"></div>
   <div class="ice-cubes">
     <div class="ice-cube ice-cube-1"></div>
     <div class="ice-cube ice-cube-2"></div>
     <div class="ice-cube ice-cube-3"></div>
   </div>
   <div class="lemon-slice"></div>
   <div class="leaves">
     <div class="leave leave-1"></div>
     <div class="leave leave-2"></div>
     <div class="leave leave-3"></div>
   </div>
   <div class="straw"></div>
   <div class="straw-surface"></div>
   <div class="shadow"></div>
  </div>
</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Knewave&display=swap" rel="stylesheet">

    <link href="css/bootstrap.css" rel="stylesheet" />
    <link href="css/rotating-card.css" rel="stylesheet" />
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar1' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
  </body>
</html>

app/views/pages/home.html.erb
<div class= "fond">
  <div class="home_bannier_container" style= "height: 60vh; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=asset_path "bars_bannier.jpg" %>); background-size: cover; background-position: bottom;" >
    <h1 class="home_bannier" style= "size: 100rem"> Barit </h1>
    <p class= "home_bannier_baseline"> Bests bars in France </p>
  </div>


  <div class="home_d-flex">
    
    <div class="home_card" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%=asset_path "sick_party.jpg" %>); background-size: cover;">
      <div class="home_card-body">
        <h5 class="home_card-title">Privatize a bar</h5>
        <p class="home_card-text">to organize immmemorable events</p>
        <%= form_tag("bars/", method: "get") do %>
        <%# <%= label_tag(:city, "Search a bar in a specific city:", class: "home_label_tag") %>
        <br>
        <%= text_field_tag :city, nil, placeholder: 'Type the city here', class:"type_a_city"  %>
        <br>
        <%= submit_tag("Search",class: "btn btn-primary bouton_search color_home") %>
        <% end %>
      </div>
    </div>

    <div class="home_card" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%=asset_path "rent_your_bar.jpg" %>); background-size: cover;">
        <div class="home_card-body">
          <h5 class="home_card-title">Rent your bar</h5>
          <p class="home_card-text">for one night</p>
          <%= link_to 'Propose a bar', new_bar_path, class:"btn btn-primary propose_a_bar color_home" %>
        </div>
    </div>
  </div>
</div>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/new.html.erb
<div class="container">
    <h1>Select the date </h1>
    <%= simple_form_for([@bar, @reservation]) do |f| %>
    <%= f.input :date %>
    <%= f.submit class: "btn btn-primary color_home"%>
    <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
<h1>Let a review</h1>

<%= simple_form_for([@bar, @review]) do |r| %>
  <%= r.input :content %>
  <%= r.input :rating, collection: Review::RATING, include_blank: false %>
  <%= r.submit class: "btn btn-primary color_home"%>
<% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar1.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon" id="navbarit">

    <%= link_to "home", root_path, class: "btn btn-primary mr-3 color_home" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <%if user_signed_in?%>
            <li class="nav-item dropdown">
                <%= image_tag "avatar_true.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to "Dashboard", dashboard_path , class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <%end%>
        </ul>
    </div>
</div>